#
FLAGS =

all:
	cd basic;     $(MAKE) -i CFLAGS=$(FLAGS)
	cd dict;      $(MAKE) -i CFLAGS=$(FLAGS)
	cd prio;      $(MAKE) -i CFLAGS=$(FLAGS)
	cd graph;     $(MAKE) -i CFLAGS=$(FLAGS)
	cd plane;     $(MAKE) -i CFLAGS=$(FLAGS)
	cd demo;      $(MAKE) -i CFLAGS=$(FLAGS)
	cd window;    $(MAKE) -i CFLAGS=$(FLAGS)

clean:
	cd basic;     $(MAKE) -i clean
	cd dict;      $(MAKE) -i clean
	cd prio;      $(MAKE) -i clean
	cd graph;     $(MAKE) -i clean
	cd plane;     $(MAKE) -i clean
	cd demo;      $(MAKE) -i clean
	cd window;    $(MAKE) -i clean
